services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: streamlit-app

    restart: always

    depends_on:
      map-init:
        condition: service_completed_successfully

    # If you are in development, uncomment the following lines to expose the streamlit app to your host machine.
    # Traefik will automatically route the traffic to the correct container in production.
    # ports:
    #   - "8501:8501"

    volumes:
      - config:/streamlit-app/config:ro
      - data:/streamlit-app/data:ro
      - figure:/streamlit-app/figure:ro
      - map_data:/streamlit-app/map_data:ro

  map-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: map-init

    restart: on-failure

    environment:
      - map_geomorph_key=${map_geomorph_key}

    volumes:
      - map_data:/streamlit-app/map_data:rw

  cron-tasks:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron-tasks

    restart: always

    environment:
      - tilsig_username=${tilsig_username}
      - tilsig_password=${tilsig_password}
      - frost_client_id=${frost_client_id}

    volumes:
      - config:/streamlit-app/config
      - data:/streamlit-app/data
      - figure:/streamlit-app/figure

volumes:
  config:
  figure:
  data:
  map_data:
